#include "data/filter/AnswerBotFilter.hpp"

namespace sedd {


bool AnswerBotFilter::process(DataDumpFileType_t, pugi::xml_node& row) {
    try {
        auto attr = row.attribute("UserId");
        if (!attr.empty() && attr.as_int() == AIBOT_UID) {
            return true;
        }

        // Some 
        attr = row.attribute("OwnerUserId");
        if (!attr.empty() && attr.as_int() == AIBOT_UID) {
            return true;
        }
    } catch (...) { // NOLINT
        
    }

    return false;
}

std::string AnswerBotFilter::getSummary() {
    return "genAI (misinformation generator) answers generated by the official tool Answer Bot (user ID -2) have been "
        "stripped from Posts. Full nuking from PostHistory is not supported at this time due to computational "
        "requirements, but will be supported in a future version. These changes may leave PostHistory in an "
        "inconsistent state. If the misinformation generator answers have been edited, there may be PostHistory "
        "entries that point to non-existent posts.";
}

}
