name: Static analysis runs
on:
  pull_request:
    branches: [ master ]

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-tidy
        run: |
          sudo apt-get update && sudo apt upgrade -y
          sudo apt-get install -y clang-tidy

          clang-tidy --version
      - name: Generate fixes.yml
        run: |
          cd transformer
          mkdir build 
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DLINT=ON -DLINT_EXPORT=ON
          make -j 2
          
      - name: Run clang-tidy-pr-comments action
        uses: platisd/clang-tidy-pr-comments@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clang_tidy_fixes: transformer/build/fixes.yml
          request_changes: true
          suggestions_per_comment: 10
