name: Data dump transformer build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        working-directory: ./transformer/
    steps:
      - uses: actions/checkout@main
      - name: Install deps (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update && sudo apt upgrade -y
      - name: Print environment
        run: |
          cmake --version
      - name: Run build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSEDD_SANITIZE=ON
          cmake --build . -j 2
      - name: Run test
        run: |
          cd build
          cmake --build . -j 2 --target test

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./transformer/
    steps:
      - uses: actions/checkout@main
      - name: Install deps
        run: |
          sudo apt update && sudo apt upgrade -y
      - name: Check clang-tidy
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DLINT=ON -DLINT_WARNINGS_ARE_ERRORS=ON
          cmake --build . -j 2
