name: Pypi and GH binary uploads 

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  publish-downloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pkginfo
          pip install -r requirements.txt
          pip install setuptools wheel build
      - name: Build package
        run: python3 -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        permissions:
          id-token: write
